[package]
name = "locate-header"
version = "0.1.0"
authors = ["Danny Browning <danny.browning@protectwise.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pkg-config = "0.3"
log = "0.4"

[dev-dependencies]
env_logger = "0.6"
